<a href="https://colab.research.google.com/github/Carolaynebarret/DataConnect/blob/main/Mini_Desafio_DataConnec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Carregamento dos Dados e Função de Diagnóstico

Primeiro, vamos importar as bibliotecas necessárias, definir os caminhos dos arquivos e criar uma função auxiliar para adivinhar a chave primária de um DataFrame, que será usada para verificar duplicatas por chave. Em seguida, definimos a função principal `diagnose_dataframe` que executa todas as verificações solicitadas para um único DataFrame.

In [6]:
import pandas as pd
import numpy as np

# Caminhos dos arquivos CSV (assumindo que estão na pasta /content/dados/)
file_paths = {
    'apontamentos': '/content/dados/dc_apontamentos.csv',
    'projetos': '/content/dados/dc_projetos.csv',
    'clientes': '/content/dados/dc_clientes.csv',
    'analistas': '/content/dados/dc_analistas.csv',
    'satisfacao': '/content/dados/dc_satisfacao.csv',
}

# Dicionário para armazenar os DataFrames
dfs = {}

In [7]:
# Função auxiliar para tentar adivinhar a chave primária de um DataFrame
def guess_primary_key(df_name, df_columns):
    potential_keys = [
        f'{df_name}_id',
        'id',
        f'cd_{df_name.replace('dc_', '')}', # Adaptado para 'dc_projetos' -> 'cd_projetos'
        f'{df_name.replace('dc_', '')}Id',
        'ID'
    ]
    for pk in potential_keys:
        if pk in df_columns:
            return pk
    return None

In [8]:
def diagnose_dataframe(df_name, df):
    print(f"\n{'='*50}\n--- Diagnóstico para: {df_name.upper()} ---\n{'='*50}")

    # 1. Quantas linhas e colunas
    print(f"\n1. Dimensões do DataFrame: {df.shape[0]} linhas, {df.shape[1]} colunas")

    # 2. Nomes das colunas
    print("\n2. Nomes das Colunas:")
    for col in df.columns:
        print(f"  - {col}")

    # 3. 10 primeiras linhas
    print("\n3. 10 Primeiras Linhas:")
    display(df.head(10))

    # 4. Tipos de cada coluna
    print("\n4. Tipos de Dados das Colunas (`df.info()`):")
    df.info()

    # 5. Nulos por coluna
    null_counts = df.isnull().sum()
    print("\n5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):")
    if null_counts.sum() > 0:
        display(null_counts[null_counts > 0])
    else:
        print("  Não há valores nulos em nenhuma coluna.")

    # 6. Linhas duplicadas
    full_duplicates = df.duplicated().sum()
    print(f"\n6. Linhas Duplicadas Completas: {full_duplicates}")

    # Duplicatas pela chave primária
    pk = guess_primary_key(df_name, df.columns)
    if pk:
        pk_duplicates = df.duplicated(subset=[pk]).sum()
        print(f"   Duplicatas pela chave primária '{pk}': {pk_duplicates}")
        if pk_duplicates > 0:
            print(f"   Exemplos de linhas duplicadas pela chave '{pk}':")
            display(df[df.duplicated(subset=[pk], keep=False)].sort_values(by=pk).head())
    else:
        print(f"   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou '{df_name}_id') para '{df_name}'. Não foi possível verificar duplicatas por chave.")

    # 7. Valores únicos de colunas categóricas e espaços em branco
    print("\n7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):")
    object_cols = df.select_dtypes(include='object').columns
    if object_cols.empty:
        print("  Não há colunas do tipo 'object' para analisar.")
    else:
        for col in object_cols:
            print(f"\n  - Coluna '{col}':")
            unique_vals = df[col].astype(str).unique()
            if len(unique_vals) <= 50: # Mostrar valores únicos se não forem muitos
                print(f"    Valores únicos ({len(unique_vals)}): {unique_vals.tolist()}")
            else:
                print(f"    {len(unique_vals)} valores únicos (mostrando os 5 primeiros): {unique_vals[:5].tolist()}...")

            # Verificar espaços em branco no início/fim
            # Usar str.strip() para garantir que espaços em branco sejam identificados
            has_leading_trailing_spaces = df[col].astype(str).apply(lambda x: x != x.strip()).any()
            if has_leading_trailing_spaces:
                # Encontrar um exemplo de valor com espaços
                example_value = df[col][df[col].astype(str).apply(lambda x: x != x.strip())].iloc[0]
                print(f"    AVISO: Existem valores com espaços em branco no início ou fim nesta coluna. Exemplo: '{example_value}'")
            else:
                print("    Não foram encontrados valores com espaços em branco no início ou fim.")

    # 8. Datas: formatos inconsistentes
    print("\n8. Análise de Colunas de Data:")
    # Incluir colunas object e datetime64 para análise
    potential_date_cols = df.select_dtypes(include=['object', 'datetime64']).columns.tolist()
    found_inconsistent_date = False

    if not potential_date_cols:
        print("  Nenhuma coluna de data potencial identificada.")
    else:
        for col in potential_date_cols:
            # Tentar converter para datetime, forçando erros para NaT
            temp_date_series = pd.to_datetime(df[col], errors='coerce')

            # Se houver NaTs introduzidos, mas não todas as linhas, há inconsistência ou valores não-data
            num_na_after_coerce = temp_date_series.isnull().sum()
            num_na_original = df[col].isnull().sum()

            if df[col].dtype == 'object' and num_na_after_coerce > num_na_original:
                # Se mais NaNs foram introduzidos, significa que havia valores que não eram datas válidas
                print(f"  AVISO: Coluna '{col}' (tipo object) contém datas com formatos inconsistentes ou valores não-data.\n    Valores que não puderam ser convertidos: {df[col][temp_date_series.isnull() & ~df[col].isnull()].unique().tolist()}")
                found_inconsistent_date = True
            elif df[col].dtype == 'object' and num_na_after_coerce == 0 and num_na_original == 0:
                print(f"  Coluna '{col}' (tipo object) parece conter datas válidas em formato consistente (todos convertidos com sucesso).")
            elif df[col].dtype == 'datetime64':
                print(f"  Coluna '{col}' já é do tipo datetime64.")

        if not found_inconsistent_date:
            print("  Todas as colunas de data identificadas parecem ter formatos consistentes ou já são do tipo datetime.")

    # 9. Outliers
    print("\n9. Análise de Outliers (Exemplos Específicos e Estatísticas Descritivas):")
    numeric_cols = df.select_dtypes(include=np.number).columns
    if numeric_cols.empty:
        print("  Não há colunas numéricas para análise de outliers.")
    else:
        print("  Estatísticas descritivas para colunas numéricas (incluindo quartis para detecção simples de outliers):")
        display(df[numeric_cols].describe())

        # Verificações específicas de outliers
        if df_name == 'apontamentos' and 'horas_apontadas' in df.columns:
            outliers_apontamentos = df[df['horas_apontadas'] > 24]
            if not outliers_apontamentos.empty:
                print(f"\n  AVISO: '{df_name}' - Existem {len(outliers_apontamentos)} apontamentos com mais de 24 horas (`horas_apontadas` > 24):")
                display(outliers_apontamentos.head())
            else:
                print(f"\n  '{df_name}' - Nenhum apontamento com mais de 24 horas encontrado em `horas_apontadas`.")

        if df_name == 'projetos' and 'valor_contrato' in df.columns:
            # Detecção de outliers usando IQR para 'valor_contrato'
            Q1 = df['valor_contrato'].quantile(0.25)
            Q3 = df['valor_contrato'].quantile(0.75)
            IQR = Q3 - Q1
            upper_bound = Q3 + 1.5 * IQR
            lower_bound = Q1 - 1.5 * IQR
            outliers_contrato = df[(df['valor_contrato'] < lower_bound) | (df['valor_contrato'] > upper_bound)]
            if not outliers_contrato.empty:
                print(f"\n  AVISO: '{df_name}' - Existem {len(outliers_contrato)} projetos com `valor_contrato` fora dos limites IQR (possíveis outliers):")
                display(outliers_contrato.head())
            else:
                print(f"\n  '{df_name}' - Nenhuma anomalia de `valor_contrato` detectada pelo método IQR simples.")

    print(f"\n{'='*50}\n--- Fim do Diagnóstico para: {df_name.upper()} ---\n{'='*50}\n")

## 2. Executando o Diagnóstico para Cada Arquivo

Agora, vamos carregar cada um dos 5 arquivos CSV para DataFrames e aplicar a função `diagnose_dataframe` que acabamos de definir. Isso nos dará uma visão detalhada do estado de cada conjunto de dados individualmente.

In [9]:
# Carregar cada arquivo e executar o diagnóstico
for name, path in file_paths.items():
    try:
        dfs[name] = pd.read_csv(path)
        diagnose_dataframe(name, dfs[name])
    except FileNotFoundError:
        print(f"ERRO: Arquivo '{path}' não encontrado. Verifique o caminho ou se ele foi carregado corretamente.\n")
    except Exception as e:
        print(f"ERRO ao processar o arquivo '{path}': {e}\n")

==================================================
--- Diagnóstico para: APONTAMENTOS ---
==================================================

1. Dimensões do DataFrame: 9879 linhas, 6 colunas

2. Nomes das Colunas:
  - apontamento_id
  - projeto_id
  - analista_id
  - data
  - horas
  - atividade

3. 10 Primeiras Linhas:

  apontamento_id projeto_id analista_id        data horas            atividade
0      APT002473    PRJ0032      ANL006  2026-03-23     6  Reunião com cliente
1      APT004798    PRJ0064      ANL008  2026-05-08   6.5         Apresentação
2      APT005566    PRJ0079      ANL012  2025-06-02     6               Coleta
3      APT000099    PRJ0003      ANL009  2025-09-15   4.5         Documentação
4      APT009367    PRJ0134      ANL009  2026-01-22     4            Modelagem
5      APT008582    PRJ0121      ANL009  05/04/2026     8               Testes
6      APT006641    PRJ0093      ANL020  11/09/2024     2               Testes
7      APT006423    PRJ0089      ANL022  2024-09-11   4.5               Coleta
8      APT007648    PRJ0109      ANL019  2026-03-27     6            Modelagem
9      APT006902    PRJ0098      ANL018  10/15/2025     7         Apresentação

4. Tipos de Dados das Colunas (`df.info()`):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   apontamento_id  9879 non-null   object
 1   projeto_id      9879 non-null   object
 2   analista_id     9879 non-null   object
 3   data            9879 non-null   object
 4   horas           9879 non-null   object
 5   atividade       9879 non-null   object
dtypes: object(6)
memory usage: 463.2+ KB

5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):
  Não há valores nulos em nenhuma coluna.

6. Linhas Duplicadas Completas: 80
   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou 'apontamentos_id') para 'apontamentos'. Não foi possível verificar duplicatas por chave.

7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):

  - Coluna 'apontamento_id':
    9799 valores únicos (mostrando os 5 primeiros): ['APT002473', 'APT004798', 'APT005566', 'APT000099', 'APT009367']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'projeto_id':
    140 valores únicos (mostrando os 5 primeiros): ['PRJ0032', 'PRJ0064', 'PRJ0079', 'PRJ0003', 'PRJ0134']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'analista_id':
    Valores únicos (24): ['ANL006', 'ANL008', 'ANL012', 'ANL009', 'ANL020', 'ANL022', 'ANL019', 'ANL018', 'ANL015', 'ANL004', 'ANL014', 'ANL021', 'ANL013', 'ANL023', 'ANL001', 'ANL002', 'ANL017', 'ANL016', 'ANL003', 'ANL011', 'ANL007', 'ANL024', 'ANL010', 'ANL005']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data':
    2037 valores únicos (mostrando os 5 primeiros): ['2026-03-23', '2026-05-08', '2025-06-02', '2025-09-15', '2026-01-22']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'horas':
    Valores únicos (23): ['6', '6.5', '4.5', '4', '8', '2', '7', '5', '2.5', '8.5', '3', '3,5', '6,5', '5.5', '7.5', '8,5', '4,5', '3.5', '2,5', '5,5', '7,5', '-4.0', '240.0']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'atividade':
    Valores únicos (15): ['Reunião com cliente', 'Apresentação', 'Coleta', 'Documentação', 'Modelagem', 'Testes', 'REUNIÃO COM CLIENTE', 'ETL', 'Dashboard', 'DOCUMENTAÇÃO', 'MODELAGEM', 'DASHBOARD', 'COLETA', 'APRESENTAÇÃO', 'TESTES']
    Não foram encontrados valores com espaços em branco no início ou fim.

8. Análise de Colunas de Data:

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

  AVISO: Coluna 'apontamento_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

,projeto_id,cliente_id,nome_projeto,tipo_servico,squad,status,data_inicio,data_fim_prevista,data_fim_real,horas_vendidas,valor_contrato
0,PRJ0001,CLI013,Dashboard BI - Windsor,Dashboard B.I.,Delta,CONCLUÍDO,2024-03-19,2024-05-06,08/05/2024,288,NaN
1,PRJ0002,CLI022,Diagnóstico de Dados - Umbu,Diagnóstico de Dados,Alpha,Cancelado,2024-10-01,2024-10-28,NaN,89,24044.51
2,PRJ0003,CLI051,Pipeline de Dados - Cristal,Pipeline de Dados,Charlie,Concluído,2025-06-16,20/10/2025,10/15/2025,423,91525.58
3,PRJ0004,CLI060,Dashboard BI - Kairós,Dashboard BI,Echo,Concluído,2024-03-19,25-abr-2024,2024-04-26,220,47409.01
4,PRJ0005,CLI020,Modelo Preditivo - Duna,Modelo Preditivo,Echo,Concluído,09/12/2024,02/27/2025,2025-03-12,338,"61.970,49"
5,PRJ0006,CLI048,Pipeline de Dados - Pantanal,Pipeline de Dados,Bravo,Concluído,26-fev-2025,2025-06-16,2025-07-09,515,110285.35
6,PRJ0007,CLI021,Data Warehouse - Quartzo,Data Warehouse,Delta,Concluído,08/13/2024,2025-02-17,2025-02-20,852,169819.61
7,PRJ0008,CLI041,Data Warehouse - Everest,Data Warehouse,Echo,Em andamento,2026-02-16,2026-09-04,NaN,743,133841.27
8,PRJ0009,CLI031,Dashboard BI - Everest,Dashboard BI,Echo,Concluído,2025-10-13,2025-11-17,17-nov-2025,157,"34.835,02"
9,PRJ0010,CLI001,Modelo Preditivo - Umbu,Modelo Preditivo,Alpha,Concluído,2024-07-08,22/10/2024,10/21/2024,578,98986.73

4. Tipos de Dados das Colunas (`df.info()`):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projeto_id         141 non-null    object
 1   cliente_id         141 non-null    object
 2   nome_projeto       141 non-null    object
 3   tipo_servico       141 non-null    object
 4   squad              141 non-null    object
 5   status             141 non-null    object
 6   data_inicio        141 non-null    object
 7   data_fim_prevista  141 non-null    object
 8   data_fim_real      128 non-null    object
 9   horas_vendidas     141 non-null    int64
 10  valor_contrato     134 non-null    object
dtypes: int64(1), object(10)
memory usage: 12.2+ KB

5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):

data_fim_real     13
valor_contrato     7
dtype: int64

6. Linhas Duplicadas Completas: 1
   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou 'projetos_id') para 'projetos'. Não foi possível verificar duplicatas por chave.

7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):

  - Coluna 'projeto_id':
    140 valores únicos (mostrando os 5 primeiros): ['PRJ0001', 'PRJ0002', 'PRJ0003', 'PRJ0004', 'PRJ0005']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'cliente_id':
    54 valores únicos (mostrando os 5 primeiros): ['CLI013', 'CLI022', 'CLI051', 'CLI060', 'CLI020']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'nome_projeto':
    87 valores únicos (mostrando os 5 primeiros): ['Dashboard BI - Windsor', 'Diagnóstico de Dados - Umbu', 'Pipeline de Dados - Cristal', 'Dashboard BI - Kairós', 'Modelo Preditivo - Duna']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'tipo_servico':
    Valores únicos (20): ['Dashboard B.I.', 'Diagnóstico de Dados', 'Pipeline de Dados', 'Dashboard BI', 'Modelo Preditivo', 'Data Warehouse', 'diagnóstico de dados', 'DASHBOARD BI', 'Treinamento', '  Dashboard BI', 'dashboard bi', 'DATA WAREHOUSE', 'treinamento', '  Data Warehouse', 'DIAGNÓSTICO DE DADOS', 'pipeline de dados', 'data warehouse', 'PIPELINE DE DADOS', '  Pipeline de Dados', 'modelo preditivo']
    AVISO: Existem valores com espaços em branco no início ou fim nesta coluna. Exemplo: '  Dashboard BI'

  - Coluna 'squad':
    Valores únicos (6): ['Delta', 'Alpha', 'Charlie', 'Echo', 'Bravo', 'Foxtrot']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'status':
    Valores únicos (5): ['CONCLUÍDO', 'Cancelado', 'Concluído', 'Em andamento', 'EM ANDAMENTO']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_inicio':
    132 valores únicos (mostrando os 5 primeiros): ['2024-03-19', '2024-10-01', '2025-06-16', '09/12/2024', '26-fev-2025']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_fim_prevista':
    131 valores únicos (mostrando os 5 primeiros): ['2024-05-06', '2024-10-28', '20/10/2025', '25-abr-2024', '02/27/2025']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_fim_real':
    118 valores únicos (mostrando os 5 primeiros): ['08/05/2024', 'nan', '10/15/2025', '2024-04-26', '2025-03-12']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'valor_contrato':
    134 valores únicos (mostrando os 5 primeiros): ['nan', '24044.51', '91525.58', '47409.01', '61.970,49']...
    Não foram encontrados valores com espaços em branco no início ou fim.

8. Análise de Colunas de Data:
  AVISO: Coluna 'projeto_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['PRJ0001', 'PRJ0002', 'PRJ0003', 'PRJ0004', 'PRJ0005', 'PRJ0006', 'PRJ0007', 'PRJ0008', 'PRJ0009', 'PRJ0010', 'PRJ0011', 'PRJ0012', 'PRJ0013', 'PRJ0014', 'PRJ0015', 'PRJ0016', 'PRJ0017', 'PRJ0018', 'PRJ0019', 'PRJ0020', 'PRJ0021', 'PRJ0022', 'PRJ0023', 'PRJ0024', 'PRJ0025', 'PRJ0026', 'PRJ0027', 'PRJ0028', 'PRJ0029', 'PRJ0030', 'PRJ0031', 'PRJ0032', 'PRJ0033', 'PRJ0034', 'PRJ0035', 'PRJ0036', 'PRJ0037', 'PRJ0038', 'PRJ0039', 'PRJ0040', 'PRJ0041', 'PRJ0042', 'PRJ0043', 'PRJ0044', 'PRJ0045', 'PRJ0046', 'PRJ0047', 'PRJ0048', 'PRJ0049', 'PRJ0050', 'PRJ0051', 'PRJ0052', 'PRJ0053', 'PRJ0054', 'PRJ0055', 'PRJ0056', 'PRJ0057', 'PRJ0058', 'PRJ0059', 'PRJ0060', 'PRJ0061', 'PRJ0062', 'PRJ0063', 'PRJ0064', 'PRJ0065', 'PRJ0066', 'PRJ0067', 'PRJ0068', 'PRJ0069', 'PRJ0070', 'PRJ0071', 'PRJ0072', 'PRJ0073', 'PRJ0074', 'PRJ0075', 'PRJ0076', 'PRJ0077', 'PRJ0078', 'PRJ0079', 'PRJ0080', 'PRJ0081', 'PRJ0082', 'PRJ0083', 'PRJ0084', 'PRJ0085', 'PRJ0086', 'PRJ0087', 'PRJ0088', 'PRJ0089', 'PRJ0090', 'PRJ0091', 'PRJ0092', 'PRJ0093', 'PRJ0094', 'PRJ0095', 'PRJ0096', 'PRJ0097', 'PRJ0098', 'PRJ0099', 'PRJ0100', 'PRJ0101', 'PRJ0102', 'PRJ0103', 'PRJ0104', 'PRJ0105', 'PRJ0106', 'PRJ0107', 'PRJ0108', 'PRJ0109', 'PRJ0110', 'PRJ0111', 'PRJ0112', 'PRJ0113', 'PRJ0114', 'PRJ0115', 'PRJ0116', 'PRJ0117', 'PRJ0118', 'PRJ0119', 'PRJ0120', 'PRJ0121', 'PRJ0122', 'PRJ0123', 'PRJ0124', 'PRJ0125', 'PRJ0126', 'PRJ0127', 'PRJ0128', 'PRJ0129', 'PRJ0130', 'PRJ0131', 'PRJ0132', 'PRJ0133', 'PRJ0134', 'PRJ0135', 'PRJ0136', 'PRJ0137', 'PRJ0138', 'PRJ0139', 'PRJ0140']
  AVISO: Coluna 'cliente_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['CLI013', 'CLI022', 'CLI051', 'CLI060', 'CLI020', 'CLI048', 'CLI021', 'CLI041', 'CLI031', 'CLI001', 'CLI030', 'CLI054', 'CLI050', 'CLI009', 'CLI018', 'CLI040', 'CLI017', 'CLI006', 'CLI002', 'CLI044', 'CLI042', 'CLI012', 'CLI036', 'CLI049', 'CLI019', 'CLI056', 'CLI059', 'CLI038', 'CLI029', 'CLI037', 'CLI032', 'CLI008', 'CLI035', 'CLI025', 'CLI010', 'CLI047', 'CLI055', 'CLI023', 'CLI052', 'CLI057', 'CLI027', 'CLI016', 'CLI024', 'CLI014', 'CLI007', 'CLI004', 'CLI034', 'CLI015', 'CLI058', 'CLI026', 'CLI033', 'CLI011', 'CLI046', 'CLI028']
  AVISO: Coluna 'nome_projeto' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Dashboard BI - Windsor', 'Diagnóstico de Dados - Umbu', 'Pipeline de Dados - Cristal', 'Dashboard BI - Kairós', 'Modelo Preditivo - Duna', 'Pipeline de Dados - Pantanal', 'Data Warehouse - Quartzo', 'Data Warehouse - Everest', 'Dashboard BI - Everest', 'Modelo Preditivo - Umbu', 'Diagnóstico de Dados - Serena', 'Data Warehouse - Aurora', 'Dashboard BI - Horizonte', 'Data Warehouse - Basalto', 'Dashboard BI - Aurora', 'Treinamento - Duna', 'Pipeline de Dados - Duna', 'Dashboard BI - Granito', 'Dashboard BI - Xingu', 'Pipeline de Dados - Granito', 'Dashboard BI - Duna', 'Data Warehouse - Ébano', 'Diagnóstico de Dados - Laguna', 'Data Warehouse - Windsor', 'Diagnóstico de Dados - Granito', 'Treinamento - Cristal', 'Data Warehouse - Cristal', 'Diagnóstico de Dados - Xingu', 'Modelo Preditivo - Basalto', 'Data Warehouse - Duna', 'Pipeline de Dados - Dunas', 'Diagnóstico de Dados - Everest', 'Data Warehouse - Xingu', 'Diagnóstico de Dados - Dunas', 'Data Warehouse - Dunas', 'Treinamento - Laguna', 'Modelo Preditivo - Coral', 'Dashboard BI - Orion', 'Dashboard BI - Cristal', 'Pipeline de Dados - Kairós', 'Dashboard BI - Serena', 'Dashboard BI - Umbu', 'Diagnóstico de Dados - Cristal', 'Pipeline de Dados - Boreal', 'Modelo Preditivo - Quartzo', 'Modelo Preditivo - Laguna', 'Pipeline de Dados - Tucano', 'Modelo Preditivo - Pantanal', 'Pipeline de Dados - Everest', 'Treinamento - Granito', 'Modelo Preditivo - Everest', 'Dashboard BI - Quartzo', 'Treinamento - Quartzo', 'Treinamento - Umbu', 'Pipeline de Dados - Aurora', 'Data Warehouse - Serena', 'Modelo Preditivo - Xingu', 'Pipeline de Dados - Basalto', 'Diagnóstico de Dados - Horizonte', 'Dashboard BI - Coral', 'Diagnóstico de Dados - Kairós', 'Treinamento - Tucano', 'Diagnóstico de Dados - Orion', 'Treinamento - Rubi', 'Diagnóstico de Dados - Tucano', 'Treinamento - Dunas', 'Treinamento - Horizonte', 'Data Warehouse - Granito', 'Treinamento - Coral', 'Modelo Preditivo - Orion', 'Diagnóstico de Dados - Windsor', 'Treinamento - Serena', 'Dashboard BI - Ébano', 'Dashboard BI - Rubi', 'Pipeline de Dados - Ipê', 'Diagnóstico de Dados - Basalto', 'Treinamento - Xingu', 'Pipeline de Dados - Rubi', 'Data Warehouse - Boreal', 'Modelo Preditivo - Aurora', 'Modelo Preditivo - Granito', 'Modelo Preditivo - Horizonte', 'Pipeline de Dados - Serena', 'Pipeline de Dados - Ébano', 'Diagnóstico de Dados - Âncora', 'Treinamento - Ébano', 'Modelo Preditivo - Tucano']
  AVISO: Coluna 'tipo_servico' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Dashboard B.I.', 'Diagnóstico de Dados', 'Pipeline de Dados', 'Dashboard BI', 'Modelo Preditivo', 'Data Warehouse', 'diagnóstico de dados', 'DASHBOARD BI', 'Treinamento', '  Dashboard BI', 'dashboard bi', 'DATA WAREHOUSE', 'treinamento', '  Data Warehouse', 'DIAGNÓSTICO DE DADOS', 'pipeline de dados', 'data warehouse', 'PIPELINE DE DADOS', '  Pipeline de Dados', 'modelo preditivo']
  AVISO: Coluna 'squad' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Delta', 'Alpha', 'Charlie', 'Echo', 'Bravo', 'Foxtrot']
  AVISO: Coluna 'status' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['CONCLUÍDO', 'Cancelado', 'Concluído', 'Em andamento', 'EM ANDAMENTO']
  AVISO: Coluna 'data_inicio' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['09/12/2024', '26-fev-2025', '08/13/2024', '09/02/2026', '15-out-2024', '06/12/2024', '01-mar-2024', '10/06/2025', '14/07/2025', '13-set-2024', '09/30/2024', '22/01/2024', '22-jan-2024', '02/21/2025', '18/07/2025', '01-abr-2025', '03/25/2025', '05/08/2024', '21-nov-2024', '01/12/2026', '03/09/2025', '14-jun-2024', '01/31/2025', '21/04/2025', '05-nov-2024', '05/11/2026', '17/02/2025', '03-set-2024', '03/03/2025', '28/07/2025', '20-mai-2024', '10/07/2024', '06/03/2025', '07-mai-2025', '08/05/2025', '17/06/2024', '14-out-2024', '12/02/2025', '16/03/2026', '05-jun-2024', '08/07/2025', '14/01/2025', '15-abr-2024', '11/17/2025', '15/01/2025', '15-abr-2026', '07/01/2025', '22/07/2025', '06-out-2025', '01/09/2024', '23/09/2024', '31-mar-2025', '01/21/2026', '05/02/2024', '28-out-2024', '04/16/2026', '08/05/2026', '20-set-2024', '08/25/2025']
  AVISO: Coluna 'data_fim_prevista' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['20/10/2025', '25-abr-2024', '02/27/2025', '22/10/2024', '10-set-2025', '07/13/2026', '17/03/2025', '03-out-2025', '02/18/2025', '03/12/2025', '10-abr-2025', '01/23/2026', '01/11/2024', '15-jun-2026', '02/20/2024', '22/07/2024', '24-fev-2025', '08/18/2025', '27/03/2025', '26-mar-2024', '11/19/2024', '01/05/2026', '24-abr-2026', '09/22/2025', '31/03/2025', '19-mai-2025', '05/07/2025', '24/12/2024', '04-jul-2024', '03/17/2025', '14/03/2025', '11-nov-2025', '09/08/2025', '25/11/2024', '15-out-2026', '06/16/2025', '26/11/2025', '26-ago-2025', '09/20/2024', '25/09/2025', '01-mai-2025', '06/08/2026', '02/09/2026', '17-jan-2025', '05/07/2024', '16-jun-2026', '04/07/2024', '02-jun-2025', '08/06/2025', '01/12/2025', '30-jun-2025', '11/08/2024', '19/01/2026', '10-jul-2025', '04/08/2024', '01/06/2026', '14-jul-2025', '06/23/2026']
  AVISO: Coluna 'data_fim_real' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['2024-04-26', '2025-03-12', '2025-07-09', '2025-02-20', '17-nov-2025', '2025-09-09', '2025-01-03', '2024-11-14', '15/12/2025', '16-jun-2026', '2025-11-18', '2025-02-14', '2024-03-25', '2026-01-26', '08-abr-2026', '2025-04-14', '2024-11-04', '2024-10-31', '14-out-2024', '2026-06-15', '2024-02-12', '2024-06-24', '2025-04-03', '24-jun-2025', '2025-02-26', '2025-08-14', '2025-08-04', '2025-09-29', '09-jun-2025', '2024-12-12', '2025-01-06', '2026-03-02', '13/11/2025', '27-dez-2024', '2026-04-22', '2025-11-20', '2024-10-14', '2025-04-29', '04-abr-2024', '2025-05-13', '2025-06-05', '2025-02-25', '26/05/2026', '23-mar-2026', '2024-07-08', '2025-03-17', '2024-11-12', '2025-08-18', '27/02/2025', '03-nov-2025', '2025-11-03', '2025-09-03', '2024-06-14', '24/10/2025', '21-jul-2025', '2025-07-17', '2025-12-01', '2025-09-22', '09-jun-2026', '2025-10-17', '2024-09-23', '2024-11-19', '2026-01-07', '23/08/2024', '18-nov-2024', '2025-04-28', '2026-06-01', '2024-06-25', '05-jun-2026', '2025-03-04', '2025-05-05', '2024-06-13', '2025-12-12', '25-abr-2025', '2026-06-10', '2025-02-17', '2026-05-04', '2025-08-21', '14/06/2024', '13-mai-2024', '2026-02-13', '2024-05-31', '2025-08-25', '2026-06-02', '12-jun-2026', '2025-07-03', '2024-04-08', '23/02/2026', '03-abr-2024', '2025-07-14', '2024-12-16', '2026-02-09']
  AVISO: Coluna 'valor_contrato' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['24044.51', '91525.58', '47409.01', '61.970,49', '110285.35', '169819.61', '133841.27', '34.835,02', '98986.73', '45106.31', '192040.56', '86.065,04', '124698.57', '80815.04', '24522.73', '81.420,19', '33713.51', '58782.26', '31273.69', '55.221,62', '61660.77', '67942.93', '66.769,09', '226034.49', '65949.12', '26036.00', '138.848,86', '26952.84', '13187.13', '109279.97', '32.582,01', '98617.32', '44063.56', '118710.70', '81.526,72', '32109.95', '121568.75', '25741.22', '104.592,71', '179318.65', '18197.78', '14415.23', '41.488,68', '94886.30', '58003.72', '44.527,48', '64256.30', '77022.28', '63128.16', '63.708,25', '14496.88', '94992.70', '99999999.00', '69.371,89', '30416.99', '41412.12', '31362.53', '14.524,47', '84086.09', '91756.72', '100834.44', '35.258,80', '88024.12', '49588.63', '10708.30', '61.251,11', '41051.78', '42220.95', '59.713,92', '7810.06', '38453.52', '25211.01', '54.464,83', '93831.25', '76866.87', '37946.56', '202.435,52', '79900.27', '130140.93', '49493.22', '20.255,45', '87154.63', '16415.49', '10300.07', '68.036,82', '34390.78', '35508.10', '8914.68', '39805.28', '88125.84', '60214.44', '21.233,45', '82761.34', '57168.86', '26963.54', '120.059,58', '23588.76', '101146.75', '56632.62', '10.174,16', '190237.28', '7767.36', '11559.92', '86.422,20', '35001.21', '27195.65', '19334.01', '70.933,53', '48393.79', '75911.35', '10.837,13', '90391.56', '104487.92', '192219.19', '84.756,41', '95107.02', '39390.08', '21189.82', '24.019,21', '60058.14', '57304.23', '37955.92', '48.685,67', '96306.00', '77705.40', '31886.85', '102.409,86', '68139.53', '59123.59', '140979.54', '13.899,29', '25492.05', '118718.29']

9. Análise de Outliers (Exemplos Específicos e Estatísticas Descritivas):
  Estatísticas descritivas para colunas numéricas (incluindo quartis para detecção simples de outliers):

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

       horas_vendidas
count      141.000000
mean       327.382979
std        225.486447
min         51.000000
25%        149.000000
50%        285.000000
75%        430.000000
max       1030.000000

ERRO ao processar o arquivo '/content/dados/dc_projetos.csv': unsupported operand type(s) for -: 'str' and 'str'


==================================================
--- Diagnóstico para: CLIENTES ---
==================================================

1. Dimensões do DataFrame: 62 linhas, 7 colunas

2. Nomes das Colunas:
  - cliente_id
  - cliente
  - setor
  - porte
  - cidade
  - uf
  - data_cadastro

3. 10 Primeiras Linhas:

,cliente_id,cliente,setor,porte,cidade,uf,data_cadastro
0,CLI001,Umbu S.A.,NaN,Pequeno,Rio de Janeiro,Rio de Janeiro,2021-10-13
1,CLI002,Xingu S.A.,Indústria,Médio,Florianópolis,SC,2021-03-07
2,CLI003,Aurora S.A.,Saúde,Médio,Curitiba,PR,2021-02-24
3,CLI004,Rubi Ltda,Logística,Pequeno,Florianópolis,SC,2024-04-21
4,CLI005,Ipê S.A.,Logística,Pequeno,Belo Horizonte,MG,15/11/2021
5,CLI006,Granito Participações,Indústria,Pequeno,São Paulo,SP,06-jan-2023
6,CLI007,Coral Participações,Educação,Grande,Fortaleza,CE,02/03/2025
7,CLI008,Orion Holding,Logística,Pequeno,São Paulo,SP,2022-08-24
8,CLI009,Basalto Brasil,Energia,Médio,Fortaleza,CE,2024-12-13
9,CLI010,Cristal S.A.,EDUCAÇÃO,Grande,Curitiba,PR,2025-10-18

4. Tipos de Dados das Colunas (`df.info()`):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     62 non-null     object
 1   cliente        62 non-null     object
 2   setor          57 non-null     object
 3   porte          62 non-null     object
 4   cidade         62 non-null     object
 5   uf             62 non-null     object
 6   data_cadastro  62 non-null     object
dtypes: object(7)
memory usage: 3.5+ KB

5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):

setor    5
dtype: int64

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

6. Linhas Duplicadas Completas: 2
   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou 'clientes_id') para 'clientes'. Não foi possível verificar duplicatas por chave.

7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):

  - Coluna 'cliente_id':
    60 valores únicos (mostrando os 5 primeiros): ['CLI001', 'CLI002', 'CLI003', 'CLI004', 'CLI005']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'cliente':
    60 valores únicos (mostrando os 5 primeiros): ['Umbu S.A.  ', 'Xingu S.A.', 'Aurora S.A.', 'Rubi Ltda', 'Ipê S.A.']...
    AVISO: Existem valores com espaços em branco no início ou fim nesta coluna. Exemplo: 'Umbu S.A.  '

  - Coluna 'setor':
    Valores únicos (18): ['nan', 'Indústria', 'Saúde', 'Logística', 'Educação', 'Energia', 'EDUCAÇÃO', ' Agronegócio ', 'Serviços Financeiros', 'Varejo', 'Setor Público', 'Tecnologia', ' Serviços Financeiros ', 'SETOR PÚBLICO', 'Agronegócio', ' Saúde ', 'SERVIÇOS FINANCEIROS', 'ENERGIA']
    AVISO: Existem valores com espaços em branco no início ou fim nesta coluna. Exemplo: ' Agronegócio '

  - Coluna 'porte':
    Valores únicos (3): ['Pequeno', 'Médio', 'Grande']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'cidade':
    Valores únicos (10): ['Rio de Janeiro', 'Florianópolis', 'Curitiba', 'Belo Horizonte', 'São Paulo', 'Fortaleza', 'Salvador', 'Recife', 'Brasília', 'Porto Alegre']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'uf':
    Valores únicos (19): ['Rio de Janeiro', 'SC', 'PR', 'MG', 'SP', 'CE', 'BA', 'pe', 'RJ', 'PE', 'Brasília', 'sc', 'RS', 'DF', 'pr', 'Curitiba', 'df', 'Recife', 'rs']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_cadastro':
    60 valores únicos (mostrando os 5 primeiros): ['2021-10-13', '2021-03-07', '2021-02-24', '2024-04-21', '15/11/2021']...
    Não foram encontrados valores com espaços em branco no início ou fim.

8. Análise de Colunas de Data:
  AVISO: Coluna 'cliente_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['CLI001', 'CLI002', 'CLI003', 'CLI004', 'CLI005', 'CLI006', 'CLI007', 'CLI008', 'CLI009', 'CLI010', 'CLI011', 'CLI012', 'CLI013', 'CLI014', 'CLI015', 'CLI016', 'CLI017', 'CLI018', 'CLI019', 'CLI020', 'CLI021', 'CLI022', 'CLI023', 'CLI024', 'CLI025', 'CLI026', 'CLI027', 'CLI028', 'CLI029', 'CLI030', 'CLI031', 'CLI032', 'CLI033', 'CLI034', 'CLI035', 'CLI036', 'CLI037', 'CLI038', 'CLI039', 'CLI040', 'CLI041', 'CLI042', 'CLI043', 'CLI044', 'CLI045', 'CLI046', 'CLI047', 'CLI048', 'CLI049', 'CLI050', 'CLI051', 'CLI052', 'CLI053', 'CLI054', 'CLI055', 'CLI056', 'CLI057', 'CLI058', 'CLI059', 'CLI060']
  AVISO: Coluna 'cliente' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Umbu S.A.  ', 'Xingu S.A.', 'Aurora S.A.', 'Rubi Ltda', 'Ipê S.A.', 'Granito Participações', 'Coral Participações', 'Orion Holding  ', 'Basalto Brasil', 'Cristal S.A.', 'Horizonte S.A.', 'Laguna Ltda', 'Windsor Brasil', 'Xingu Ltda', 'Windsor Holding  ', 'Boreal Ltda', 'Granito Holding', 'Duna Azul Brasil', 'Xingu Holding', 'Duna Azul Holding', 'Quartzo Group', 'Umbu Ltda  ', 'Tucano Group', 'Aurora Brasil', 'Umbu Participações', 'Ipê Holding', 'Quartzo Holding', 'Rubi Holding', 'Dunas Participações  ', 'Serena S.A.', 'Everest Brasil', 'Coral Holding', 'Xingu Brasil', 'Orion S.A.', 'Serena Holding', 'Cristal Holding  ', 'Serena Group', 'Dunas S.A.', 'Coral Brasil', 'Kairós S.A.', 'Everest Group', 'Ébano S.A.', 'Rubi S.A.  ', 'Pantanal Ltda', 'Manaca Participações', 'Âncora Holding', 'Boreal Holding', 'Pantanal Holding', 'Cristal Ltda', 'Horizonte Group  ', 'Cristal Group', 'Granito Brasil', 'Vertente Brasil', 'Aurora Group', 'Quartzo Participações', 'Horizonte Participações', 'Windsor Participações  ', 'Rubi Participações', 'Dunas Brasil', 'Kairós Ltda']
  AVISO: Coluna 'setor' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Indústria', 'Saúde', 'Logística', 'Educação', 'Energia', 'EDUCAÇÃO', ' Agronegócio ', 'Serviços Financeiros', 'Varejo', 'Setor Público', 'Tecnologia', ' Serviços Financeiros ', 'SETOR PÚBLICO', 'Agronegócio', ' Saúde ', 'SERVIÇOS FINANCEIROS', 'ENERGIA']
  AVISO: Coluna 'porte' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Pequeno', 'Médio', 'Grande']
  AVISO: Coluna 'cidade' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Rio de Janeiro', 'Florianópolis', 'Curitiba', 'Belo Horizonte', 'São Paulo', 'Fortaleza', 'Salvador', 'Recife', 'Brasília', 'Porto Alegre']
  AVISO: Coluna 'uf' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Rio de Janeiro', 'SC', 'PR', 'MG', 'SP', 'CE', 'BA', 'pe', 'RJ', 'PE', 'Brasília', 'sc', 'RS', 'DF', 'pr', 'Curitiba', 'df', 'Recife', 'rs']
  AVISO: Coluna 'data_cadastro' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['15/11/2021', '06-jan-2023', '02/03/2025', '01/07/2022', '30-dez-2023', '08/03/2024', '28/05/2023', '11-out-2021', '11/10/2021', '18/11/2025', '27-nov-2021', '02/09/2021', '07/10/2024', '13-fev-2021', '05/26/2021', '08/07/2023', '26-nov-2025', '08/28/2024', '28/04/2021', '07-nov-2023', '11/01/2025', '31/05/2021', '06-dez-2025', '01/18/2024']

9. Análise de Outliers (Exemplos Específicos e Estatísticas Descritivas):
  Não há colunas numéricas para análise de outliers.

==================================================
--- Fim do Diagnóstico para: CLIENTES ---
==================================================


==================================================
--- Diagnóstico para: ANALISTAS ---
==================================================

1. Dimensões do DataFrame: 24 linhas, 6 colunas

2. Nomes das Colunas:
  - analista_id
  - analista
  - squad
  - senioridade
  - custo_hora
  - data_admissao

3. 10 Primeiras Linhas:

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

,analista_id,analista,squad,senioridade,custo_hora,data_admissao
0,ANL001,Ana Barbosa,ALPHA,Senior,"150,00",2021-12-07
1,ANL002,Bruno Ipiranga,Bravo,Pleno,95.00,2021-08-30
2,ANL003,Carla Esteves,Charlie,Junior,55.00,2024-12-26
3,ANL004,Diego Freitas,Delta,Especialista,210.00,2025-07-28
4,ANL005,Elisa Werneck,Echo,Pleno,95.00,24/10/2023
5,ANL006,Felipe Duarte,Foxtrot,Pleno,"95,00",02-nov-2021
6,ANL007,Gabriela Werneck,Alpha,Especialista,210.00,04/02/2022
7,ANL008,Henrique Lopes,Bravo,Pleno,95.00,2024-09-05
8,ANL009,Isabela Nunes,CHARLIE,Pleno,95.00,2022-02-17
9,ANL010,João Lopes,Delta,Junior,55.00,2025-11-17

4. Tipos de Dados das Colunas (`df.info()`):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   analista_id    24 non-null     object
 1   analista       24 non-null     object
 2   squad          24 non-null     object
 3   senioridade    24 non-null     object
 4   custo_hora     24 non-null     object
 5   data_admissao  24 non-null     object
dtypes: object(6)
memory usage: 1.3+ KB

5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):
  Não há valores nulos em nenhuma coluna.

6. Linhas Duplicadas Completas: 0
   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou 'analistas_id') para 'analistas'. Não foi possível verificar duplicatas por chave.

7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):

  - Coluna 'analista_id':
    Valores únicos (24): ['ANL001', 'ANL002', 'ANL003', 'ANL004', 'ANL005', 'ANL006', 'ANL007', 'ANL008', 'ANL009', 'ANL010', 'ANL011', 'ANL012', 'ANL013', 'ANL014', 'ANL015', 'ANL016', 'ANL017', 'ANL018', 'ANL019', 'ANL020', 'ANL021', 'ANL022', 'ANL023', 'ANL024']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'analista':
    Valores únicos (24): ['Ana Barbosa', 'Bruno Ipiranga', 'Carla Esteves', 'Diego Freitas', 'Elisa Werneck', 'Felipe Duarte', 'Gabriela Werneck', 'Henrique Lopes', 'Isabela Nunes', 'João Lopes', 'Karina Barbosa', 'Lucas Henriques', 'Mariana Ribeiro', 'Nelson Xavier', 'Olívia Henriques', 'Paulo Freitas', 'Queila Xavier', 'Rafael Nunes', 'Sofia Xavier', 'Thiago Freitas', 'Úrsula Marques', 'Vinícius Henriques', 'Wanda Oliveira', 'Yuri Henriques']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'squad':
    Valores únicos (9): ['ALPHA', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Alpha', 'CHARLIE', 'ECHO']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'senioridade':
    Valores únicos (4): ['Senior', 'Pleno', 'Junior', 'Especialista']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'custo_hora':
    Valores únicos (7): ['150,00', '95.00', '55.00', '210.00', '95,00', '210,00', '150.00']
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_admissao':
    Valores únicos (24): ['2021-12-07', '2021-08-30', '2024-12-26', '2025-07-28', '24/10/2023', '02-nov-2021', '04/02/2022', '2024-09-05', '2022-02-17', '2025-11-17', '2023-06-03', '25/02/2025', '11-set-2023', '04/13/2022', '2022-04-29', '2023-09-23', '2023-04-12', '2025-11-29', '17/12/2025', '30-out-2025', '08/19/2021', '2022-07-14', '2023-05-18', '2022-08-31']
    Não foram encontrados valores com espaços em branco no início ou fim.

8. Análise de Colunas de Data:
  AVISO: Coluna 'analista_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['ANL001', 'ANL002', 'ANL003', 'ANL004', 'ANL005', 'ANL006', 'ANL007', 'ANL008', 'ANL009', 'ANL010', 'ANL011', 'ANL012', 'ANL013', 'ANL014', 'ANL015', 'ANL016', 'ANL017', 'ANL018', 'ANL019', 'ANL020', 'ANL021', 'ANL022', 'ANL023', 'ANL024']
  AVISO: Coluna 'analista' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Ana Barbosa', 'Bruno Ipiranga', 'Carla Esteves', 'Diego Freitas', 'Elisa Werneck', 'Felipe Duarte', 'Gabriela Werneck', 'Henrique Lopes', 'Isabela Nunes', 'João Lopes', 'Karina Barbosa', 'Lucas Henriques', 'Mariana Ribeiro', 'Nelson Xavier', 'Olívia Henriques', 'Paulo Freitas', 'Queila Xavier', 'Rafael Nunes', 'Sofia Xavier', 'Thiago Freitas', 'Úrsula Marques', 'Vinícius Henriques', 'Wanda Oliveira', 'Yuri Henriques']
  AVISO: Coluna 'squad' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['ALPHA', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Alpha', 'CHARLIE', 'ECHO']
  AVISO: Coluna 'senioridade' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Senior', 'Pleno', 'Junior', 'Especialista']
  AVISO: Coluna 'custo_hora' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['150,00', '95.00', '55.00', '210.00', '210,00', '150.00']
  AVISO: Coluna 'data_admissao' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['24/10/2023', '02-nov-2021', '04/02/2022', '25/02/2025', '11-set-2023', '04/13/2022', '17/12/2025', '30-out-2025', '08/19/2021']

9. Análise de Outliers (Exemplos Específicos e Estatísticas Descritivas):
  Não há colunas numéricas para análise de outliers.

==================================================
--- Fim do Diagnóstico para: ANALISTAS ---
==================================================


==================================================
--- Diagnóstico para: SATISFACAO ---
==================================================

1. Dimensões do DataFrame: 103 linhas, 5 colunas

2. Nomes das Colunas:
  - pesquisa_id
  - projeto_id
  - data_pesquisa
  - nota_nps
  - comentario

3. 10 Primeiras Linhas:

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

,pesquisa_id,projeto_id,data_pesquisa,nota_nps,comentario
0,PSQ0001,PRJ0001,2024-05-27,NaN,"Resultado ok, prazo apertado."
1,PSQ0002,PRJ0003,2025-10-20,10.0,Documentação impecável.
2,PSQ0003,PRJ0004,2024-05-08,9.0,Documentação impecável.
3,PSQ0004,PRJ0005,2025-03-27,7.0,"Bom projeto, comunicação pode melhorar."
4,PSQ0005,PRJ0006,17/07/2025,6.0,Suporte demorou a responder.
5,PSQ0006,PRJ0010,06-nov-2024,9.0,Ganhamos agilidade nas decisões.
6,PSQ0007,PRJ0011,09/15/2025,7.0,"Bom projeto, comunicação pode melhorar."
7,PSQ0008,PRJ0013,2025-01-21,8.0,Atendeu ao combinado.
8,PSQ0009,PRJ0014,2024-11-27,6.0,Precisamos refazer parte do painel.
9,PSQ0010,PRJ0015,2025-12-29,8.0,"Resultado ok, prazo apertado."

4. Tipos de Dados das Colunas (`df.info()`):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pesquisa_id    103 non-null    object
 1   projeto_id     103 non-null    object
 2   data_pesquisa  103 non-null    object
 3   nota_nps       95 non-null     float64
 4   comentario     103 non-null    object
dtypes: float64(1), object(4)
memory usage: 4.2+ KB

5. Contagem de Valores Nulos por Coluna (apenas colunas com nulos):

nota_nps    8
dtype: int64

6. Linhas Duplicadas Completas: 0
   AVISO: Não foi possível identificar uma chave primária (ex: 'id' ou 'satisfacao_id') para 'satisfacao'. Não foi possível verificar duplicatas por chave.

7. Análise de Colunas Categóricas (Valores Únicos e Espaços em Branco):

  - Coluna 'pesquisa_id':
    103 valores únicos (mostrando os 5 primeiros): ['PSQ0001', 'PSQ0002', 'PSQ0003', 'PSQ0004', 'PSQ0005']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'projeto_id':
    103 valores únicos (mostrando os 5 primeiros): ['PRJ0001', 'PRJ0003', 'PRJ0004', 'PRJ0005', 'PRJ0006']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'data_pesquisa':
    100 valores únicos (mostrando os 5 primeiros): ['2024-05-27', '2025-10-20', '2024-05-08', '2025-03-27', '17/07/2025']...
    Não foram encontrados valores com espaços em branco no início ou fim.

  - Coluna 'comentario':
    Valores únicos (10): ['Resultado ok, prazo apertado.', 'Documentação impecável.', 'Bom projeto, comunicação pode melhorar.', 'Suporte demorou a responder.', 'Ganhamos agilidade nas decisões.', 'Atendeu ao combinado.', 'Precisamos refazer parte do painel.', 'O painel virou rotina da diretoria.', 'Entrega no prazo e time muito atencioso.', 'Atraso significativo na entrega.']
    Não foram encontrados valores com espaços em branco no início ou fim.

8. Análise de Colunas de Data:
  AVISO: Coluna 'pesquisa_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['PSQ0001', 'PSQ0002', 'PSQ0003', 'PSQ0004', 'PSQ0005', 'PSQ0006', 'PSQ0007', 'PSQ0008', 'PSQ0009', 'PSQ0010', 'PSQ0011', 'PSQ0012', 'PSQ0013', 'PSQ0014', 'PSQ0015', 'PSQ0016', 'PSQ0017', 'PSQ0018', 'PSQ0019', 'PSQ0020', 'PSQ0021', 'PSQ0022', 'PSQ0023', 'PSQ0024', 'PSQ0025', 'PSQ0026', 'PSQ0027', 'PSQ0028', 'PSQ0029', 'PSQ0030', 'PSQ0031', 'PSQ0032', 'PSQ0033', 'PSQ0034', 'PSQ0035', 'PSQ0036', 'PSQ0037', 'PSQ0038', 'PSQ0039', 'PSQ0040', 'PSQ0041', 'PSQ0042', 'PSQ0043', 'PSQ0044', 'PSQ0045', 'PSQ0046', 'PSQ0047', 'PSQ0048', 'PSQ0049', 'PSQ0050', 'PSQ0051', 'PSQ0052', 'PSQ0053', 'PSQ0054', 'PSQ0055', 'PSQ0056', 'PSQ0057', 'PSQ0058', 'PSQ0059', 'PSQ0060', 'PSQ0061', 'PSQ0062', 'PSQ0063', 'PSQ0064', 'PSQ0065', 'PSQ0066', 'PSQ0067', 'PSQ0068', 'PSQ0069', 'PSQ0070', 'PSQ0071', 'PSQ0072', 'PSQ0073', 'PSQ0074', 'PSQ0075', 'PSQ0076', 'PSQ0077', 'PSQ0078', 'PSQ0079', 'PSQ0080', 'PSQ0081', 'PSQ0082', 'PSQ0083', 'PSQ0084', 'PSQ0085', 'PSQ0086', 'PSQ0087', 'PSQ0088', 'PSQ0089', 'PSQ0090', 'PSQ0091', 'PSQ0092', 'PSQ0093', 'PSQ0094', 'PSQ0095', 'PSQ0096', 'PSQ0097', 'PSQ0098', 'PSQ0099', 'PSQ0100', 'PSQ0101', 'PSQ0102', 'PSQ0103']
  AVISO: Coluna 'projeto_id' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['PRJ0001', 'PRJ0003', 'PRJ0004', 'PRJ0005', 'PRJ0006', 'PRJ0010', 'PRJ0011', 'PRJ0013', 'PRJ0014', 'PRJ0015', 'PRJ0016', 'PRJ0017', 'PRJ0018', 'PRJ0019', 'PRJ0020', 'PRJ0022', 'PRJ0023', 'PRJ0024', 'PRJ0025', 'PRJ0026', 'PRJ0028', 'PRJ0029', 'PRJ0030', 'PRJ0031', 'PRJ0032', 'PRJ0033', 'PRJ0034', 'PRJ0035', 'PRJ0037', 'PRJ0039', 'PRJ0041', 'PRJ0043', 'PRJ0044', 'PRJ0045', 'PRJ0046', 'PRJ0047', 'PRJ0049', 'PRJ0050', 'PRJ0051', 'PRJ0052', 'PRJ0053', 'PRJ0055', 'PRJ0057', 'PRJ0059', 'PRJ0060', 'PRJ0061', 'PRJ0064', 'PRJ0065', 'PRJ0066', 'PRJ0067', 'PRJ0068', 'PRJ0069', 'PRJ0070', 'PRJ0071', 'PRJ0072', 'PRJ0073', 'PRJ0074', 'PRJ0075', 'PRJ0076', 'PRJ0077', 'PRJ0078', 'PRJ0079', 'PRJ0080', 'PRJ0084', 'PRJ0086', 'PRJ0087', 'PRJ0088', 'PRJ0089', 'PRJ0090', 'PRJ0091', 'PRJ0092', 'PRJ0093', 'PRJ0094', 'PRJ0096', 'PRJ0097', 'PRJ0098', 'PRJ0099', 'PRJ0100', 'PRJ0102', 'PRJ0104', 'PRJ0105', 'PRJ0107', 'PRJ0108', 'PRJ0109', 'PRJ0110', 'PRJ0112', 'PRJ0113', 'PRJ0116', 'PRJ0117', 'PRJ0119', 'PRJ0123', 'PRJ0124', 'PRJ0125', 'PRJ0126', 'PRJ0127', 'PRJ0128', 'PRJ0130', 'PRJ0132', 'PRJ0134', 'PRJ0135', 'PRJ0137', 'PRJ0139', 'PRJ0140']
  AVISO: Coluna 'data_pesquisa' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['17/07/2025', '06-nov-2024', '09/15/2025', '26/03/2025', '02-dez-2025', '03/03/2025', '30/04/2025', '06-fev-2026', '11/06/2024', '21/02/2024', '01-jul-2024', '04/21/2025', '16/06/2025', '09-abr-2025', '04/08/2024', '15/05/2026', '06-mai-2026', '11/04/2024', '03/06/2026', '08-abr-2026', '12/30/2024', '11/03/2025', '24-nov-2025', '03/24/2025', '10/11/2025', '04-ago-2025', '12/09/2024', '02/10/2024', '22-nov-2024', '01/14/2026', '01/07/2024', '23-out-2025', '07/14/2025', '05/05/2025', '17-jul-2024', '06/24/2026', '25/08/2025', '18-jun-2024', '08/29/2025', '18/06/2026', '15-jul-2025', '11/21/2024', '13/02/2026']
  AVISO: Coluna 'comentario' (tipo object) contém datas com formatos inconsistentes ou valores não-data.
    Valores que não puderam ser convertidos: ['Resultado ok, prazo apertado.', 'Documentação impecável.', 'Bom projeto, comunicação pode melhorar.', 'Suporte demorou a responder.', 'Ganhamos agilidade nas decisões.', 'Atendeu ao combinado.', 'Precisamos refazer parte do painel.', 'O painel virou rotina da diretoria.', 'Entrega no prazo e time muito atencioso.', 'Atraso significativo na entrega.']

9. Análise de Outliers (Exemplos Específicos e Estatísticas Descritivas):
  Estatísticas descritivas para colunas numéricas (incluindo quartis para detecção simples de outliers):

/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_948/2298784008.py:78: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_date_series = pd.to_datetime(df[col], errors='coerce')

        nota_nps
count  95.000000
mean    8.421053
std     1.601721
min     3.000000
25%     8.000000
50%     9.000000
75%    10.000000
max    10.000000

==================================================
--- Fim do Diagnóstico para: SATISFACAO ---
==================================================

## 3. Verificações de Consistência Entre Arquivos

Por fim, vamos realizar as verificações de consistência entre os DataFrames, garantindo que as chaves estrangeiras referenciem IDs existentes nos DataFrames relacionados.

In [10]:
print(f"\n{'='*50}\n--- Verificações de Consistência Entre Arquivos ---\n{'='*50}")

# 1. Verificar se todo projeto_id que aparece em apontamentos existe em projetos
if 'apontamentos' in dfs and 'projetos' in dfs and 'projeto_id' in dfs['apontamentos'].columns and 'projeto_id' in dfs['projetos'].columns:
    apontamentos_projetos_ids = dfs['apontamentos']['projeto_id'].dropna().unique()
    projetos_ids = dfs['projetos']['projeto_id'].dropna().unique()
    missing_projetos_in_apontamentos = np.setdiff1d(apontamentos_projetos_ids, projetos_ids)
    if len(missing_projetos_in_apontamentos) > 0:
        print(f"\nAVISO: 'projeto_id' em `apontamentos` não encontrados em `projetos`: {len(missing_projetos_in_apontamentos)} IDs.\n  Exemplos: {missing_projetos_in_apontamentos[:5].tolist()}")
    else:
        print("\nTodos os 'projeto_id' em `apontamentos` existem em `projetos`.")
else:
    print("\nNão foi possível verificar a consistência de 'projeto_id' entre `apontamentos` e `projetos` (arquivos/colunas ausentes ou renomeadas).")

# 2. Verificar se todo cliente_id de projetos existe em clientes
if 'projetos' in dfs and 'clientes' in dfs and 'cliente_id' in dfs['projetos'].columns and 'cliente_id' in dfs['clientes'].columns:
    projetos_clientes_ids = dfs['projetos']['cliente_id'].dropna().unique()
    clientes_ids = dfs['clientes']['cliente_id'].dropna().unique()
    missing_clientes_in_projetos = np.setdiff1d(projetos_clientes_ids, clientes_ids)
    if len(missing_clientes_in_projetos) > 0:
        print(f"\nAVISO: 'cliente_id' em `projetos` não encontrados em `clientes`: {len(missing_clientes_in_projetos)} IDs.\n  Exemplos: {missing_clientes_in_projetos[:5].tolist()}")
    else:
        print("\nTodos os 'cliente_id' em `projetos` existem em `clientes`.")
else:
    print("\nNão foi possível verificar a consistência de 'cliente_id' entre `projetos` e `clientes` (arquivos/colunas ausentes ou renomeadas).")

# 3. Verificar se todo analista_id de apontamentos existe em analistas
if 'apontamentos' in dfs and 'analistas' in dfs and 'analista_id' in dfs['apontamentos'].columns and 'analista_id' in dfs['analistas'].columns:
    apontamentos_analistas_ids = dfs['apontamentos']['analista_id'].dropna().unique()
    analistas_ids = dfs['analistas']['analista_id'].dropna().unique()
    missing_analistas_in_apontamentos = np.setdiff1d(apontamentos_analistas_ids, analistas_ids)
    if len(missing_analistas_in_apontamentos) > 0:
        print(f"\nAVISO: 'analista_id' em `apontamentos` não encontrados em `analistas`: {len(missing_analistas_in_apontamentos)} IDs.\n  Exemplos: {missing_analistas_in_apontamentos[:5].tolist()}")
    else:
        print("\nTodos os 'analista_id' em `apontamentos` existem em `analistas`.")
else:
    print("\nNão foi possível verificar a consistência de 'analista_id' entre `apontamentos` e `analistas` (arquivos/colunas ausentes ou renomeadas).")

# 4. Verificar se todo projeto_id de satisfacao existe em projetos
if 'satisfacao' in dfs and 'projetos' in dfs and 'projeto_id' in dfs['satisfacao'].columns and 'projeto_id' in dfs['projetos'].columns:
    satisfacao_projetos_ids = dfs['satisfacao']['projeto_id'].dropna().unique()
    projetos_ids = dfs['projetos']['projeto_id'].dropna().unique()
    missing_projetos_in_satisfacao = np.setdiff1d(satisfacao_projetos_ids, projetos_ids)
    if len(missing_projetos_in_satisfacao) > 0:
        print(f"\nAVISO: 'projeto_id' em `satisfacao` não encontrados em `projetos`: {len(missing_projetos_in_satisfacao)} IDs.\n  Exemplos: {missing_projetos_in_satisfacao[:5].tolist()}")
    else:
        print("\nTodos os 'projeto_id' em `satisfacao` existem em `projetos`.")
else:
    print("\nNão foi possível verificar a consistência de 'projeto_id' entre `satisfacao` e `projetos` (arquivos/colunas ausentes ou renomeadas).")

print(f"\n{'='*50}\n--- Fim das Verificações de Consistência ---\n{'='*50}\n")

==================================================
--- Verificações de Consistência Entre Arquivos ---
==================================================

Todos os 'projeto_id' em `apontamentos` existem em `projetos`.

Todos os 'cliente_id' em `projetos` existem em `clientes`.

Todos os 'analista_id' em `apontamentos` existem em `analistas`.

Todos os 'projeto_id' em `satisfacao` existem em `projetos`.

==================================================
--- Fim das Verificações de Consistência ---
==================================================